### ISSUE TITLE
Android - Exception observed in a callback method:

### ISSUE THREAD

**Issue by rjambula** [Marketing-Suite/android-sdk#7]
Exception observed in a callback method when incorrect APP Id was provided: (APP ID was in like 2 double quotes, so it became incorrect..)
06-05 15:47:10.876 21148-21148/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.kansascity.android, PID: 21148
                                                   java.lang.NullPointerException
                                                       at experian.mobilesdk.EMSMobileSDK$1deviceRegistered.Callback(EMSMobileSDK.java:290)
                                                       at experian.mobilesdk.MessageQueue.onReceive(MessageQueue.java:200)
                                                       at experian.mobilesdk.VolleySender$1.onResponse(VolleySender.java:105)
                                                       at experian.mobilesdk.VolleySender$1.onResponse(VolleySender.java:80)

**Comment by ClientDeveloperRelations** [comment]
Weekly meeting: not observed with the latest SDK release, and will be closed/kept open based on QA findings.

**Comment by ClientDeveloperRelations** [comment]
Double quotes around the Application Id will cause an error - this should not be done.

**Comment by ClientDeveloperRelations** [comment]
Will raise issue to confirm that Application Id is a UUID.

**Comment by ClientDeveloperRelations** [comment]
I've opened up an internal feature request that the Application be confirmed as a UUID/GUID.  This is a new feature, and will be prioritized below bugs.  In the meantime please be mindful that there is no error checking in the SDK against the Application Id, which is currently only a string.

Closing this issue.
